from .groupSerializer import GroupSerializer
from .userSerializer import UserSerializer

from .albertHeijnProductSerializer import AlbertHeijnProductSerializer
from .jumboProductSerializer import JumboProductSerializer
from .coopProductSerializer import CoopProductSerializer

from .baseProductDetailsSerializer import BaseProductDetailsSerializer
from .albertHeijnProductDetailsSerializer import AlbertHeijnProductDetailsSerializer
from .jumboProductDetailsSerializer import JumboProductDetailsSerializer
from .coopProductDetailsSerializer import CoopProductDetailsSerializer


