# Generated by Django 3.0.5 on 2020-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(unique_for_date=True, verbose_name='product id')),
                ('entry_date', models.DateTimeField(null=True, verbose_name='entry date')),
            ],
        ),
    ]
