# Generated by Django 3.0.5 on 2020-05-19 12:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AlbertHeijnProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.BigIntegerField(unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
        migrations.CreateModel(
            name='AlbertHeijnProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('price_now', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_now_unit_size', models.CharField(blank=True, max_length=50)),
                ('price_unit_info', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit_info_unit_size', models.CharField(blank=True, max_length=50)),
                ('catalog_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('hq_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_medicine', models.BooleanField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.PositiveIntegerField(unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CoopProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.BigIntegerField(unique_for_date=True, verbose_name='product id')),
                ('product_url', models.CharField(max_length=500, verbose_name='product url')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
        migrations.CreateModel(
            name='CoopProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('price_now', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_now_unit_size', models.CharField(blank=True, max_length=50)),
                ('price_unit_info', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit_info_unit_size', models.CharField(blank=True, max_length=50)),
                ('catalog_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('hq_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_medicine', models.BooleanField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.BigIntegerField(unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DeenProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.CharField(max_length=100, unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
        migrations.CreateModel(
            name='DeenProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('price_now', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_now_unit_size', models.CharField(blank=True, max_length=50)),
                ('price_unit_info', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit_info_unit_size', models.CharField(blank=True, max_length=50)),
                ('catalog_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('hq_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_medicine', models.BooleanField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.BigIntegerField(unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DirkProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.BigIntegerField(unique_for_date=True, verbose_name='product id')),
                ('product_url', models.CharField(max_length=500, verbose_name='product url')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='category')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
        migrations.CreateModel(
            name='DirkProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('price_now', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_now_unit_size', models.CharField(blank=True, max_length=50)),
                ('price_unit_info', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit_info_unit_size', models.CharField(blank=True, max_length=50)),
                ('catalog_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('hq_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_medicine', models.BooleanField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.BigIntegerField(unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='JumboProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.CharField(max_length=100, unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
        migrations.CreateModel(
            name='JumboProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('price_now', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_now_unit_size', models.CharField(blank=True, max_length=50)),
                ('price_unit_info', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit_info_unit_size', models.CharField(blank=True, max_length=50)),
                ('catalog_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('hq_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_medicine', models.BooleanField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.CharField(max_length=100, unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VomarProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.CharField(max_length=255, unique_for_date=True, verbose_name='product id')),
                ('category', models.CharField(blank=True, max_length=200, verbose_name='category')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
        migrations.CreateModel(
            name='VomarProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('summary', models.TextField(blank=True)),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(blank=True, max_length=250)),
                ('price_now', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_now_unit_size', models.CharField(blank=True, max_length=50)),
                ('price_unit_info', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('price_unit_info_unit_size', models.CharField(blank=True, max_length=50)),
                ('catalog_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id')),
                ('brand', models.CharField(blank=True, max_length=200)),
                ('category', models.CharField(blank=True, max_length=200)),
                ('hq_id', models.PositiveIntegerField(blank=True, null=True)),
                ('is_medicine', models.BooleanField(blank=True, null=True)),
                ('properties', models.TextField(blank=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.CharField(max_length=255, unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
