# Generated by Django 3.0.5 on 2020-04-24 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albertheijnproduct',
            name='product_id',
            field=models.BigIntegerField(unique_for_date=True, verbose_name='product id'),
        ),
        migrations.AlterField(
            model_name='coopproduct',
            name='product_url',
            field=models.CharField(max_length=500, verbose_name='product url'),
        ),
        migrations.AlterField(
            model_name='coopproductdetails',
            name='product_id',
            field=models.BigIntegerField(unique_for_date=True, verbose_name='product id'),
        ),
    ]
