# Generated by Django 3.0.5 on 2020-04-02 22:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbertHeijnProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(unique_for_date=True, verbose_name='product id')),
                ('entry_date', models.DateTimeField(null=True, verbose_name='entry date')),
            ],
        ),
        migrations.CreateModel(
            name='ProxyList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proxy', models.CharField(max_length=30, unique=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
