# Generated by Django 3.0.5 on 2020-04-09 10:41

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200407_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albertheijnproduct',
            name='entry_date',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date'),
        ),
    ]
