# Generated by Django 3.0.5 on 2020-04-10 10:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200409_1241'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlbertHeijnProductDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_id', models.PositiveIntegerField(unique_for_date=True, verbose_name='product id')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('summary', models.TextField()),
                ('is_available', models.BooleanField(default=True)),
                ('image_url', models.CharField(max_length=250)),
                ('price_now', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price_now_unit_size', models.CharField(max_length=10)),
                ('price_unit_info', models.DecimalField(decimal_places=4, max_digits=10)),
                ('price_unit_info_unit_size', models.CharField(max_length=10)),
                ('catalog_id', models.PositiveIntegerField(verbose_name='item catalog id')),
                ('brand', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('hq_id', models.PositiveIntegerField()),
                ('is_medicine', models.BooleanField(default=True)),
                ('is_vegetarian', models.BooleanField(default=True)),
                ('has_gluten', models.BooleanField(default=True)),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
            ],
        ),
    ]
