# Generated by Django 3.0.5 on 2020-04-10 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_albertheijnproductdetails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='has_gluten',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='is_medicine',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='is_vegetarian',
            field=models.BooleanField(),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='summary',
            field=models.TextField(max_length=500),
        ),
    ]
