# Generated by Django 3.0.5 on 2020-04-10 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200410_1441'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='brand',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='catalog_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='item catalog id'),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='has_gluten',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='hq_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='image_url',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='is_medicine',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='is_vegetarian',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='price_now',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='price_now_unit_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='price_unit_info',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='price_unit_info_unit_size',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='summary',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
