# Generated by Django 3.0.5 on 2020-04-14 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_auto_20200410_1528'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='albertheijnproduct',
            options={'ordering': ['entry_date', '-product_id']},
        ),
    ]
