# Generated by Django 3.0.5 on 2020-04-14 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_auto_20200414_1052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='albertheijnproductdetails',
            name='has_gluten',
        ),
        migrations.RemoveField(
            model_name='albertheijnproductdetails',
            name='is_vegetarian',
        ),
        migrations.AddField(
            model_name='albertheijnproductdetails',
            name='properties',
            field=models.TextField(blank=True),
        ),
    ]
