# Generated by Django 3.0.5 on 2020-04-15 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_auto_20200415_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='brand',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='category',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='price_now_unit_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='price_unit_info_unit_size',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='albertheijnproductdetails',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
