# Generated by Django 3.0.5 on 2020-04-20 10:12

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_jumboproductdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='JumboProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_date', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='entry date')),
                ('product_id', models.PositiveIntegerField(unique_for_date=True, verbose_name='product id')),
            ],
            options={
                'ordering': ['entry_date', '-product_id'],
            },
        ),
    ]
