# Generated by Django 3.0.5 on 2020-04-20 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_jumboproduct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jumboproduct',
            name='product_id',
            field=models.CharField(max_length=100, unique_for_date=True, verbose_name='product id'),
        ),
    ]
