# Generated by Django 3.0.5 on 2020-04-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_coopproduct_coopproductdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='coopproduct',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
