# Generated by Django 3.0.5 on 2020-04-22 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0016_coopproduct_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopproduct',
            name='product_id',
            field=models.PositiveIntegerField(unique_for_date=True, verbose_name='product id'),
        ),
    ]
