# Generated by Django 3.0.5 on 2020-04-22 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0017_auto_20200422_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coopproduct',
            name='product_id',
            field=models.BigIntegerField(unique_for_date=True, verbose_name='product id'),
        ),
    ]
